<template>
    <div class="main-content">
      <article class="form-container" ref="content">
        <span>
        Terms of Use for the App "Aerocene"
        <br><br>
        1. SCOPE OF THESE TERMS OF USE
        <br><br>
        1.1 These Terms of Use of Studio Tomás Saraceno GmbH (hereinafter: Studio Saraceno) apply to the use of the App "Aerocene" (hereinafter: App) in addition to the terms of use made available by Apple (as the operator of the iTunes store), Google (as the operator of the Google Play store) or other providers (hereinafter collectively: App Store Operators). In case of eventual contradictions, the present Terms of Use will take precedence over those of the App Store Operators with regard to the relationship between Studio Saraceno and the relevant user. These terms do not affect the contractual relationship between the App Store Operators and the user.
        <br><br>
        1.2 These Terms of Use apply as of January 2020 and will automatically be included in the contractual relationship between you and Studio Saraceno upon registration with the App for any use of the App.
        <br><br>
        2. SCOPE OF SERVICES OF THE APP AND VERSIONS
        <br><br>
        2.1 The App is made available by Studio Saraceno free of charge via App Store Operators. The App is an art work containing an artistic experience by Studio Tomás Saraceno related to Spider/Webs (hereinafter: the App). On the basis of oracle questions submitted by you to the App and photographs of spiders or  spider webs which you upload to the App, playful oracle sayings / vibrations are randomly determined for you.
        <br><br>
        2.2 The App also contains a feature called "map against extinction", which can be accessed through the Spiderweb Button into which Spider/Web images uploaded by you and other users of the App are integrated - after being released as being suitable for publication in the App by Studio Saraceno - and which can be accessed by you and every other user of the App. Before releasing images to be part of the "map against extinction" Studio Saraceno will examine such images for their content and quality. Once such images are uploaded, they can be found on the map under the GPS data from which they were uploaded.
        <br><br>
        2.3 There is also a feature with which you can share your experience with other registered users of the App. You can also share your experience with friends not registered in the App through the App user’s external e-mail client.
        <br><br>
        2.4 With your consent given when installing the App by pushing the Button "Receive Artwork Certificate", we have the right, but not the obligation to send you a certificate which grants recognition of your contribution (uploaded spider image) to the collective artwork generated by the App.
        <br><br>
        2.5 The App is only provided in English.
        <br><br>
        3. REGISTRATION
        <br><br>
        3.1 In order to use the App, it is necessary to register via a login mask. When logging in, we ask you for a user name and your e-mail address.
        <br><br>
        4. DATA PROTECTION
        <br><br>
        <a href="policy" style="color: 'white';">Please find our privacy policy here.</a>
        <br><br>
        5. USE OF THE APP; MAINTENANCE AND SERVICE
        <br><br>
        5.1 Your right to use the App is not exclusive, not sub-licensable and not transferable.
        <br><br>
        5.2 You are responsible for making sure that there is a sufficient internet connection. You are also responsible for compliance with the system requirements necessary for the use of the App, particularly regarding the operating system used by you.
        <br><br>
        5.3 Studio Saraceno reserves the right to stop running the App at any time, restrict access to the App or the possibility of its use temporarily in whole or in part if this is necessary due to capacity limits or the security or integrity of the servers or to carry out technical measures serving the purpose of providing the services properly of with improvements (e.g. for maintenance work).
        <br><br>
        5.4 Studio Saraceno has no obligation to provide updates or upgrades for the App of to adapt the App in any other way to possible changes to hardware and/or software (in particular, operating systems).
        <br><br>
        6. YOUR DUTIES AND LIABILITY
        <br><br>
        6.1 You may neither alter the App nor interfere with the App. This also includes the transfer of viruses or spyware. Electronic attacks of any kind on the platform, the database or individual users of the App are prohibited. Every electronic attack results in immediate exclusion from use and in the institution of civil and criminal proceedings.
        <br><br>
        6.2 The App and its functions may not be used in an abusive manner. In the event of violation of Applicable German law or our Terms of Use, Studio Saraceno reserves the right to exclude you from using the App.
        <br><br>
        7. GRANT OF RIGHTS, USER GENERATED CONTENT
        <br><br>
        7.1 You grant Studio Saraceno the non-exclusive right free of charge to exploit the questions submitted by you to the oracle as well as the images of Spider/Webs uploaded by you for the purposes of the functionalities of the App provided for, in particular, to make such user-generated content and the GPS data connected to it accessible to other users of the App through the feature "map against extinction" which can be accessed through the Spider-Web Button.
        <br><br>
        7.2 In addition, the images uploaded by you into the App could be used, reproduced, modified and made available to the public in an interactive "map against extinction" on a separate Website outside of the App, after approval and release of Studio Saraceno. There is no obligation of Studio Saraceno to release an uploaded image to such "map against extinction".
        <br><br>
        7.3 You warrant that you are entitled to grant Studio Saraceno the above-mentioned rights and that the user-generated content does not violate statutory regulations or accepted principles of morality (e.g., by way of its content, its visual layout of the intended purpose).
        <br><br>
        7.4 For reasons of practicality Studio Saraceno will not credit your image with your user name. You agree that you accept this.
        <br><br>
        7.5 In the case of infringement of third-party rights for which you are responsible, you will be directly liable toward these third parties yourself. In the event of justified claims of third parties against Studio Saraceno due to such an infringement, you have the obligation to indemnify Studio Saraceno in full unless you prove that you are not responsible for the breach of duty that has caused the damage or loss.
        <br><br>
        8. DEFECTS; LIABILITY OF STUDIO SARACENO
        <br><br>
        8.1 Studio Saraceno will be liable for damage or loss only if Studio Saraceno culpably (that is, at least negligently) breaches a material contractual duty (the term "material contractual duties" meaning such duties the fulfilment of which is indispensable for the proper execution of the contract, on the compliance with which the contracting partner may generally rely and the breach is which jeopardises the achievement of the purpose of the contract), the damage or loss was caused by gross negligence or intent on the part of Studio Saraceno or Studio Saraceno has assumed a guarantee.
        <br><br>
        8.2 Studio Saraceno´s liability is limited to the typical, foreseeable damage or loss if Studio Saraceno has culpably, but not with gross negligence or intent, breached material contractual duties or its employees or agents who are not members of an executive body or key employees have breached other duties with gross negligence or intent.
        <br><br>
        8.3 Studio Saraceno´s liability under mandatory statutory provisions, in particular, under the German Product Liability Act (Produkthaftungsgesetz), and the liability for intentional act, for the injury to life, limb or health and for fraudulent failure to disclose a defect remains unaffected.
        <br><br>
        9. AMENDMENT OF THE TERMS OF USE AND SERVICES
        <br><br>
        1.1 Studio Saraceno reserves the right to modify and adapt these Terms of Use at any time and without giving reasons, unless this is unreasonable for the user. Studio Saraceno will notify you about amendments of the Terms of Use in an appropriate manner. If you do not object to the validity of the new terms of use within four weeks after notification, the amended terms of use will be deemed accepted by you. Studio Saraceno will indicate the right to object and the significance of the objection period to the user in the notification. If you object, the entitlement to use the services provided by Studio Saraceno will end and Studio Saraceno will be entitled to delete the account and the data of the relevant user.
        <br><br>
        9.1 Studio Saraceno reserves the right to change the name of the App, add or remove the services provided within the App or offer deviating services, unless this is unreasonable for the user. In particular, Studio Saraceno may adapt the scope of services to the relevant state of the art or extend it.
        <br><br>
        10. FINAL PROVISIONS
        <br><br>
        10.1 The laws of the Federal Republic of Germany apply, excluding the United Nations Convention on Contracts for the International Sale of Goods (CISG). Unless the users are consumers within the meaning of § 13 German Civil Code (BGB), Berlin is agreed to be the exclusive place of jurisdiction.
        <br><br>
        10.2 Studio Saraceno may make use of third parties, in particular, companies affiliated with it, for the purpose of performing the contract and exercising the rights arising under this declaration. Studio Saraceno has the right to transfer its rights and duties under this contractual relationship as a whole to a third party with a notification period of four weeks.
        <br><br>

        <br><br>
        Janunary 2020
        <br><br>

        <br><br>
        </span>
      </article>

      <b-btn class="ok-btn" @click="$router.back()">Ok</b-btn>
    </div>
</template>

<style lang="scss" scoped>

.main-content {
  position: absolute;
  height: 100%;
  width: 100%;
  z-index: 20;
  padding-top: 120px;
  padding-bottom: 4em;
  padding-left: 3em;
  padding-right: 2em;
  overflow: hidden;

  /* background: #000000bb; */
  text-align: left;
  display: flex;
  flex-direction: column;
  justify-content: end;
}

.form-container {
  width: 100%;
  height: 100%;
  overflow-x:hidden;
  overflow-y: scroll;

  padding-top:0%;
  padding-right: 1em;  

  scrollbar-width: thin;
  scrollbar-color:#676767#000;
}

.ok-btn {
  font-size: 18px;  
  margin-top: 2em;
  background: none;
  border: none;
  text-transform: none;    
}

</style>

<script>

import router from '../../router';

export default {
  name: 'SignUpTerms',
  data() {
    return {
    };
  },
  created() {
    this.$store.commit('flightSimulator/setVisualizationState', 6);
  },
};
</script>
